// cts_get_cts_schema — L1 + L2 tests (16 cases: P0×11 + P1×5)
// Per design doc §7 / cases.md.
// Auto-generated by mcp-orchestrator skeleton + manual review (M1 first-tool path).
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { McpClient, parseToolResult, stripVolatile } from "../_lib/mcp-client.js";

const TOOL = "cts_get_cts_schema";
const ALL_DICT_TYPES = [
  "city_tree",
  "industry_tree",
  "job_category_tree",
  "education_tree",
  "school_type_tree",
  "experience_tree",
] as const;
const SMALL_DICTS = ["education_tree", "school_type_tree", "experience_tree"] as const;
const LARGE_DICTS = ["city_tree", "industry_tree", "job_category_tree"] as const;

const OFFLINE = process.env.MCP_OFFLINE === "1";

describe.skipIf(OFFLINE)(`${TOOL} [L1+L2]`, () => {
  let client: McpClient;
  beforeAll(async () => { client = await McpClient.fromEnv(); });
  afterAll(async () => { await client.close(); });

  // ────────────────────── L1: Schema 合规 ──────────────────────

  it("[P0][L1] tools/list 中存在 cts_get_cts_schema", async () => {
    const tools = await client.listTools();
    expect(tools.find((t) => t.name === TOOL)).toBeDefined();
  });

  it("[P0][L1] annotations 与 PRD §1.3.1 一致", async () => {
    const tools = await client.listTools();
    const t = tools.find((x) => x.name === TOOL)!;
    expect(t.annotations).toMatchObject({
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: true,
    });
  });

  it("[P0][L1] inputSchema 含 schema_types + queries 两个核心参数", async () => {
    const tools = await client.listTools();
    const t = tools.find((x) => x.name === TOOL)!;
    const props = (t.inputSchema as { properties?: Record<string, unknown> }).properties ?? {};
    expect(Object.keys(props)).toEqual(expect.arrayContaining(["schema_types", "queries"]));
  });

  it("[P0][L1] schema_types items.enum 含 PRD 列出的全部 6 个字典", async () => {
    const tools = await client.listTools();
    const t = tools.find((x) => x.name === TOOL)!;
    const enumValues = (t.inputSchema as {
      properties?: { schema_types?: { items?: { enum?: string[] } } };
    }).properties?.schema_types?.items?.enum ?? [];
    expect(enumValues.sort()).toEqual([...ALL_DICT_TYPES].sort());
  });

  // ────────────────────── L2: Happy paths（5 条） ──────────────────────

  it("[P0][L2] 模式(a) 索引：不传参 → 返回 6 个字典类型", async () => {
    const r = await client.callTool(TOOL, {});
    const { data } = parseToolResult(r);
    const types = (data as { types?: Array<{ schema_type: string }> } | null)?.types ?? [];
    expect(types.length).toBe(6);
    const names = types.map((x) => x.schema_type).sort();
    expect(names).toEqual([...ALL_DICT_TYPES].sort());
  });

  it("[P0][L2] 模式(b) 全量：schema_types=[education_tree] → items 非空", async () => {
    const r = await client.callTool(TOOL, { schema_types: ["education_tree"] });
    const { data } = parseToolResult(r);
    // shape may be { items: [...] } or { results: { education_tree: {items:[...]} } } — assert "exists somewhere"
    const text = JSON.stringify(data);
    expect(text).toMatch(/本科|大专|硕士|博士/);
  });

  it("[P0][L2] 模式(b) 全量 3 小字典：edu+school+exp 都返回", async () => {
    const r = await client.callTool(TOOL, { schema_types: [...SMALL_DICTS] });
    const { data } = parseToolResult(r);
    const text = JSON.stringify(data);
    // edu / school_type / experience 各有典型词应该出现
    expect(text).toMatch(/本科|硕士|大专/);              // education
    expect(text).toMatch(/985|211|双一流|海外|普通/);    // school_type
    expect(text).toMatch(/年|应届|经验/);                // experience
  });

  it("[P0][L2] 模式(c) 解析：{education_tree, '本科'} → exact 命中且 confidence=high", async () => {
    const r = await client.callTool(TOOL, {
      queries: [{ schema_type: "education_tree", label: "本科" }],
    });
    const { data } = parseToolResult(r);
    type Item = { value: string; label: string; match_type?: string; confidence?: string; score?: number };
    const schemas = (data as { schemas?: Array<{ schema_type: string; items?: Item[] }> } | null)?.schemas ?? [];
    expect(schemas.length).toBe(1);
    expect(schemas[0].schema_type).toBe("education_tree");
    const items = schemas[0].items ?? [];
    expect(items.length).toBeGreaterThan(0);
    const exactMatch = items.find((i) => i.label === "本科" && i.match_type === "exact");
    expect(exactMatch).toBeDefined();
    expect(exactMatch?.confidence).toBe("high");
    expect(exactMatch?.score).toBe(1);
  });

  it("[P0][L2] 模式(c) 多 query：学历+城市同时解析 → 两个 schema 都有候选", async () => {
    const r = await client.callTool(TOOL, {
      queries: [
        { schema_type: "education_tree", label: "本科" },
        { schema_type: "city_tree", label: "北京" },
      ],
    });
    const { data } = parseToolResult(r);
    const text = JSON.stringify(data);
    expect(text).toMatch(/本科/);
    expect(text).toMatch(/北京/);
  });

  // ────────────────────── L2: 工具特有 / Edge / Negative（5 条） ──────────────────────

  it("[P0][L2] 模式(b) 大字典 city_tree → 应被拒绝（PRD: full-dump refused）", async () => {
    let rejected = false;
    let result: unknown = null;
    try {
      const r = await client.callTool(TOOL, { schema_types: ["city_tree"] });
      result = r;
      // 也可能 server 通过 content + isError:true 标记拒绝
      if (r.isError) rejected = true;
    } catch {
      rejected = true;
    }
    expect(rejected).toBe(true);
    if (!rejected) {
      // 如果 server 没拒绝（contradicts PRD），把它打出来让人看
      console.warn("[diff] city_tree full-dump was NOT refused. Server response:", JSON.stringify(result).slice(0, 500));
    }
  });

  it("[P1][L2] 模式(c) '本科以上' → range-equivalent 命中 '本科' + '本科及以上'，不含 '大专及以上'", async () => {
    const r = await client.callTool(TOOL, {
      queries: [{ schema_type: "education_tree", label: "本科以上" }],
    });
    const { data } = parseToolResult(r);
    const text = JSON.stringify(data);
    expect(text).toMatch(/本科/);
    // PRD: range-equivalent 仅聚同 core 的兄弟，不应跨 core 误中
    expect(text).not.toMatch(/大专及以上/);
  });

  it("[P1][L2] 模式(c) '深圳宝安' → path_subsequence 命中宝安", async () => {
    const r = await client.callTool(TOOL, {
      queries: [{ schema_type: "city_tree", label: "深圳宝安" }],
    });
    const { data } = parseToolResult(r);
    const text = JSON.stringify(data);
    expect(text).toMatch(/宝安/);
  });

  it("[P1][L2] 模式(c) 不存在的城市 '火星市' → candidates 为空或低置信", async () => {
    const r = await client.callTool(TOOL, {
      queries: [{ schema_type: "city_tree", label: "火星市" }],
    });
    const { data } = parseToolResult(r);
    const text = JSON.stringify(data);
    // 期望至少不返回 high confidence；接受空结果
    expect(text).not.toMatch(/"confidence"\s*:\s*"high"/);
  });

  it("[P1][L2] 模式(c) 非法 schema_type 'not_a_real_dict' → schema 校验错", async () => {
    let rejected = false;
    try {
      const r = await client.callTool(TOOL, {
        // @ts-expect-error — intentionally violating enum
        queries: [{ schema_type: "not_a_real_dict", label: "随便" }],
      });
      if (r.isError) rejected = true;
    } catch {
      rejected = true;
    }
    expect(rejected).toBe(true);
  });

  // ────────────────────── L2: 鉴权 ──────────────────────

  it("[P0][L2] 鉴权：无 token → 应被拒绝", async () => {
    let c: McpClient | null = null;
    let failed = false;
    try {
      c = await McpClient.fromEnv({ noAuth: true });
      const r = await c.callTool(TOOL, {});
      if (r.isError) failed = true;
    } catch {
      failed = true;
    } finally {
      try { await c?.close(); } catch { /* noop */ }
    }
    expect(failed).toBe(true);
  });

  // ────────────────────── L2: 幂等性 ──────────────────────

  it("[P0][L2] 幂等：同 query 2 次结果一致（剥除 trace_id）", async () => {
    const args = { queries: [{ schema_type: "education_tree", label: "本科" }] };
    const a = parseToolResult(await client.callTool(TOOL, args)).data;
    const b = parseToolResult(await client.callTool(TOOL, args)).data;
    expect(stripVolatile(a)).toEqual(stripVolatile(b));
  });

  // ────────────────────── Skipped — 待测试账号 ──────────────────────

  it.skip("[P0][L2] 鉴权：有 token 但无字典访问权限 → 403", () => {
    // TODO(C): 待运维提供"有 token 无字典访问权限"的测试账号
  });
});

// 抑制未使用警告（LARGE_DICTS 引用作为常量参考）
void LARGE_DICTS;
