import { type Page, type Locator } from '@playwright/test';
import type { I18n } from '../fixtures';

// POM fragment for upload-input feature area (PRD 3.2.4)
// Generated by e2e-orchestrator (source: prd)
// Merge into task.page.ts after all parallel orchestrators complete.

export class TaskPageUploadInputFragment {
  private readonly page: Page;
  private readonly i18n?: I18n;

  private readonly fileInput: Locator;

  constructor(page: Page, i18n?: I18n) {
    this.page = page;
    this.i18n = i18n;
    this.fileInput = page.locator("input[type='file']");
  }

  getFileInput(): Locator {
    return this.fileInput;
  }

  private get promptForm(): Locator {
    return this.page.locator('form').filter({ has: this.page.locator('textarea') }).first();
  }

  getAttachmentPills(): Locator {
    return this.promptForm.locator('div[class*="rounded-[10px]"]').filter({ has: this.page.locator('p') });
  }

  getAttachmentPillByName(filename: string): Locator {
    return this.promptForm.locator('div[class*="rounded-[10px]"]').filter({
      has: this.page.locator('p', { hasText: filename }),
    }).first();
  }

  getAttachmentRemoveBtnByName(filename: string): Locator {
    return this.getAttachmentPillByName(filename).getByRole('button', { name: /Remove attachment|移除附件/ });
  }

  getAttachmentFilenameByName(filename: string): Locator {
    return this.page.locator('p.truncate', { hasText: filename }).first();
  }

  getAttachmentTypeLabel(filename: string): Locator {
    return this.getAttachmentPillByName(filename).locator('p.text-muted-foreground').first();
  }

  getAttachmentThumbnail(filename: string): Locator {
    return this.getAttachmentPillByName(filename).locator('img').first();
  }

  getUploadingSpinner(): Locator {
    return this.promptForm.locator('[class*="animate-spin"]');
  }

  getFirstAttachmentRemoveBtn(): Locator {
    return this.page.getByRole('button', { name: /Remove attachment|移除附件/ }).first();
  }

  async attachFile(filePath: string): Promise<void> {
    await this.fileInput.setInputFiles(filePath);
  }

  async attachFiles(filePaths: string[]): Promise<void> {
    await this.fileInput.setInputFiles(filePaths);
  }

  async removeFirstAttachment(): Promise<void> {
    const pill = this.getAttachmentPills().first();
    await pill.hover();
    await this.getFirstAttachmentRemoveBtn().click();
  }

  async removeAttachmentByName(filename: string): Promise<void> {
    const pill = this.getAttachmentPillByName(filename);
    await pill.hover();
    await this.getAttachmentRemoveBtnByName(filename).click();
  }

  async waitForUploadComplete(filename: string, timeout = 30_000): Promise<void> {
    const pill = this.getAttachmentPillByName(filename);
    await pill.waitFor({ state: 'visible', timeout });
    // Wait for spinner to disappear (upload complete); catch if spinner never appeared (fast upload)
    await pill.locator('[class*="animate-spin"]').waitFor({ state: 'detached', timeout }).catch(() => {});
  }
}
